sudo: true

dist: trusty

language: cpp

services: 
  - mysql

compiler: gcc

install:
  - cd ~/build/HaliteChallenge/Halite/
  - ./setupWebsite.sh

  - cd ~/build/HaliteChallenge/Halite/tests
  - sudo ./install.sh

  - cp travisTests.ini tests.ini

script:
  - cd ~/build/HaliteChallenge/Halite/airesources/Java
  - javac MyBot.java

  - cd ../C++
  - g++ -std=c++11 MyBot.cpp -o MyBot.o

  - cd ~/build/HaliteChallenge/Halite/environment
  - make
  - ./environment -d 10 10 "python3 ../airesources/Python/MyBot.py" "cd ../airesources/Java; java MyBot" "../airesources/C++/MyBot.o"
    
  - cd ~/build/HaliteChallenge/Halite/tests/
  - python3 runTests.py

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
