sudo: required

dist: trusty

language: cpp

services: 
  - mysql

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

compiler: gcc

install:
  - mysql -u root -e 'create database Halite;'
 
  - cd ~/build/HaliteChallenge/Halite/website
  - ./install.sh

  - cd ~/build/HaliteChallenge/Halite/tests
  - sudo ./install.sh

  - cp travisTests.ini tests.ini

  - phpenv global 5.6

script:
  - cd ~/build/HaliteChallenge/Halite/airesources/Java
  - javac MyBot.java

  - cd ../C++
  - g++ -std=c++11 MyBot.cpp -o MyBot.o

  - cd ~/build/HaliteChallenge/Halite/environment
  - make
  - ./environment -d 10 10 "python3 ../airesources/Python/MyBot.py" "cd ../airesources/Java; java MyBot" "../airesources/C++/MyBot.o"
    
  - cd ~/build/HaliteChallenge/Halite/tests/
  - cp tests.ini ../halite.ini
  - mysql -u root < ../website/sql/Database.sql
  - sudo phpunit --stderr website/
  - cd environment
  - python3 testenv.py


notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
