sudo: true
dist: bionic
language: cpp

# https://docs.travis-ci.com/user/languages/cpp/
# Test on multiple GCC and Clang versions
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - lcov
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
            - lcov
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:

# build game environment
  - cd environment/
  - cmake .
  - make -j2

# build C++ bot
  - cd ../airesources/C++
  - make MyBot

# build Rust bot
  - cd ../Rust
  - curl -sSf https://static.rust-lang.org/rustup.sh | sh
  - cargo rustc --release -q -- -Awarnings

# build Java bot
  - cd ../Java
  - javac MyBot.java
  
# compile Python script
  - cd ../Python3
  - python -m py_compile MyBot.py

# compile mlstarterbot script
  - cd ../ML-StarterBot-Python
  - python -m py_compile MyBot.py

# build website
  - cd ../../website
  - npm config set package-lock false
  - gem install bundler
  - bundle install --path=vendor/bundle
  - npm install
  - cd ../libhaliteviz
  - npm install
  - cd ../website
  - npm run build
  - bundle exec jekyll build

# build standalone visualizer
  - cd ../tools/standalone_visualizer
  - npm install
  - cd ../../website
  - bundle exec jekyll build
  - cd ../tools/standalone_visualizer
  - npm run build
  - npm run package-linux
