sudo: required

dist: trusty

language: generic

install:
  - mysql -u root -e 'create database Halite;'

  - cd ~/build/HaliteChallenge/Halite/tests
  - cp travisTests.ini tests.ini
  - cp travisTests.ini ../halite.ini
 
  - cd ~/build/HaliteChallenge/Halite/website
  - sudo ./install.sh

  - cd ~/build/HaliteChallenge/Halite/worker
  - sudo ./install.sh 123

  - cd ~/build/HaliteChallenge/Halite/tests
  - sudo ./install.sh

script:
  - cd ~/build/HaliteChallenge/Halite/tests/
  - sudo ./runTests.sh

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
