# Specify version format
version: "{build}"

# clone directory
clone_folder: C:\Halite

# branches to build
branches:
 only:
  - master

before_build:
 - dir \s

# scripts that run after cloning repository
build_script:
 - cd C:\Halite\environment
 - .\make.bat
