# Specify version format
version: "{build}"

# clone directory
clone_folder: C:\Halite

# branches to build
branches:
 only:
  - master

# scripts that run after cloning repository
build:
 - cmd: cd C:\Halite\environment
 - cmd: environment\make.bat
