# Specify version format
version: "{build}"

# Only build when a tag is pushed
skip_non_tags: true

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: C:\Halite

# branches to build
branches:
  only:
    - master

install:
  - ps: Invoke-WebRequest https://cmake.org/files/v3.12/cmake-3.12.1-win64-x64.zip -OutFile C:\cmake.zip
  - ps: Expand-Archive c:\cmake.zip -DestinationPath c:\cmake
  - ps: dir c:\cmake
  - set path=C:\cmake\cmake-3.12.1-win64-x64\bin;%path%

# scripts that run after cloning repository
build_script:
  - cd C:\Halite\environment
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - .\make.bat

artifacts:
  - path: environment\build\Release\halite.exe
    name: halite.exe
