# Specify version format
version: "{build}"

# Only build when a tag is pushed
skip_non_tags: true

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: C:\Halite

# branches to build
branches:
  only:
    - master

#before_build:
#  - dir \s

install:
  - choco install cmake --install-directory 'C:\cmake' -y
  - set path=C:\cmake\bin;%path%

# scripts that run after cloning repository
build_script:
  - cd C:\Halite\environment
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - .\make.bat

artifacts:
  - path: environment\build\Release\halite.exe
    name: halite.exe
